# You can test locally this repo with
# populate the .env file, based on .env.template
# docker-compose up -d --build --force-recreate && docker-compose logs --follow --tail 100

version: '3.3'
services:
  git:
    build:
      context: .
    # image: ghcr.io/sredevopsdev/git-volumes-synchronizer:latest
    container_name: git
    restart: no
    env_file:
      - .env
    volumes:
      - ./git:/git:rw
  
  
