# You can test locally this repo with
# populate the .env file, based on .env.template
# docker-compose up -d --build --force-recreate && docker-compose logs --follow --tail 100

version: '3.3'
services:
  git:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ghcr.io/sredevopsdev/git-volumes-synchronizer:latest
    container_name: git-volumes-synchronizer
    restart: always
    env_file:
      - .env
    volumes:
      - ./git:/git:rw
  mysql:
    image: docker.io/mysql/mysql-server:8.0.32-1.2.11-server
    container_name: mysql
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./git/content:/var/lib/mysql:rw
    ports:
      - 3306:3306
    depends_on:
      - git

    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
      - MYSQL_HOST=%
      - MYSQL_PORT=3306    

