apiVersion: v1
kind: Secret
metadata:
  name: ghost-config-prod
  namespace: gitsync
type: Opaque
# data:
#   config.production.json: ""
stringData:
  config.production.json: |-
    {
      "url": "http://localhost:2368",
      "admin": {
        "url": "http://localhost:2368"
      },
      "server": {
        "port": 2368,
        "host": "0.0.0.0"
      },
      "database": {
        "client": "mysql",
        "connection": {
          "host": "mysql-gitsync",
          "user": "your_git_username",
          "password": "your_mysql_password",
          "database": "your_mysql_database",
          "port": "3306"
        }
      },
      "mail": {
        "transport": "Direct"
      },
      "logging": {
        "transports": [
          "file",
          "stdout"
        ]
      },
      "process": "local",
      "debug": true,
      "paths": {
        "contentPath": "/var/lib/ghost/content"
      }
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials-repo
  namespace: gitsync
stringData:
  GIT_USERNAME: "your_git_username"
  GIT_PASSWORD: ""
  GIT_TOKEN: "your_git_token"
  GIT_SSH_PRIVATE_KEY_BASE64: ""
  GIT_REPO_URL: "your_git_repo_url"
  GIT_SYNC_INTERVAL: "3600" # 1 hour, in milliseconds. The synchronization interval is used to configure the synchronization process.
  GIT_BRANCH: "your_git_branch"
  GIT_USER_EMAIL: "your_git_user_email"
---
apiVersion: v1
kind: Secret
metadata:
  name: gitsync-mysql-credentials
  namespace: gitsync
type: Opaque
stringData:
  MYSQL_DATABASE: "your_mysql_database"
  MYSQL_USER: "your_mysql_user"
  MYSQL_PASSWORD: "your_mysql_password"
  MYSQL_ROOT_PASSWORD: "your_mysql_root_password"
---
apiVersion: v1
kind: Secret
metadata:
  name: git-sync-ghost
  namespace: gitsync
stringData:
  GIT_USERNAME: "your_git_username"
  GIT_PASSWORD: ""
  GIT_TOKEN: "your_git_token"
  GIT_SSH_PRIVATE_KEY_BASE64: ""
  GIT_REPO_URL: "your_git_repo_url"
  GIT_SYNC_INTERVAL: "3600" # 1 hour, in milliseconds. The synchronization interval is used to configure the synchronization process.
  GIT_BRANCH: "your_git_branch"
  GIT_USER_EMAIL: "your_git_user_email"
