apiVersion: v1
kind: Secret
metadata:
  name: ghost-config-prod
  namespace: gitsync
type: Opaque
# data:
#   config.production.json: ""
stringData:
  config.production.json: |
    {
      "url": "http://localhost:2368",
      "admin": {
        "url": "http://localhost:2368"
      },
      "server": {
        "port": 2368,
        "host": "0.0.0.0"
      },
      "database": {
        "client": "mysql",
        "connection": {
          "host": "gitsync-mysql",
          "user": "",
          "password": "",
          "database": "",
          "port": "3306"
        }
      },
      "mail": {
        "transport": "Direct"
      },
      "logging": {
        "transports": [
          "file",
          "stdout"
        ]
      },
      "process": "local",
      "debug": true,
      "paths": {
        "contentPath": "/var/lib/ghost/content"
      }
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials-repo
  namespace: gitsync
stringData:
  GIT_USERNAME: ""
  GIT_PASSWORD: ""
  GIT_TOKEN: ""
  GIT_SSH_PRIVATE_KEY_BASE64: ""
  GIT_REPO_URL: ""
  GIT_SYNC_INTERVAL: "3600" # 1 hour, in milliseconds. The synchronization interval is used to configure the synchronization process.
  GIT_BRANCH: ""
  GIT_USER_EMAIL: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: gitsync-mysql-credentials
  namespace: gitsync
type: Opaque
stringData:
  MYSQL_DATABASE: "" # Base64 encoded, same as config.production.json
  MYSQL_PASSWORD: "" # Base64 encoded, same as config.production.json
  MYSQL_ROOT_PASSWORD: "" # Base64 encoded, if you want to connect through proxy as root
  MYSQL_USER: "" # Base64 encoded, same as config.production.json
