apiVersion: v1
kind: Secret
metadata:
  name: ghost-config-prod
  namespace: gitsync
type: Opaque
data:
  config.production.json: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: custom-cert-tls
  namespace: gitsync
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
---
apiVersion: v1
data:
  GIT_USERNAME: ""
  GIT_PASSWORD: ""
  GIT_TOKEN: ""
  GIT_SSH_PRIVATE_KEY_BASE64: ""
  GIT_REPO_URL: ""
  GIT_SYNC_INTERVAL: 3600 # 1 hour, in milliseconds. The synchronization interval is used to configure the synchronization process.
  GIT_BRANCH: ""
  GIT_USER_EMAIL: ""

kind: Secret
metadata:
  name: git-credentials-repo
  namespace: gitsync
---
apiVersion: v1
data:
  MYSQL_DATABASE: "" # Base64 encoded, same as config.production.json
  MYSQL_PASSWORD: "" # Base64 encoded, same as config.production.json
  MYSQL_ROOT_HOST: JQ== # Base64 encoded, if you want to connect through proxy as root
  MYSQL_ROOT_PASSWORD: "" # Base64 encoded, if you want to connect through proxy as root
  MYSQL_USER: "" # Base64 encoded, same as config.production.json
  MYSQL_USER_HOST: JQ== # Base64 encoded, if you want to connect through proxy as the user
kind: Secret
metadata:
  name: gitsync-mysql-credentials
  namespace: gitsync
type: Opaque
