apiVersion: v1
kind: Service
metadata:
  name: ghostsync
  namespace: gitsync
  labels:
    app: ghostsync
spec:
  ports:
  - port: 2368
    protocol: TCP
    targetPort: 2368
    name: ghostsync
  type: ClusterIP
  selector:
    app: ghostsync
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-gitsync
  namespace: gitsync
  labels:
    app: mysql-gitsync
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    name: mysql-gs
  type: ClusterIP
  selector:
    app: mysql-gitsync
