apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-gitsync
  namespace: gitsync
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: mysql-gitsync

  serviceName: mysql-gitsync
  template:
    metadata:
      labels:
        app: mysql-gitsync
    spec:
      containers:
      - name: mysql-gitsync
        envFrom:
        - secretRef:
            name: gitsync-mysql-credentials
        image: docker.io/mysql/mysql-server:8.0.32-1.2.11-server
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - |
              mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "show databases;" || exit 1
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - containerPort: 3306
          name: mysql-gs
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - |
              mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "show databases;" || exit 1
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "0"
            memory: "0"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001


        startupProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - |
              mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "show databases;" || exit 1
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5

        volumeMounts:
        - mountPath: /var/lib/mysql
          mountPropagation: HostToContainer
          name: mysql-gitsync-vol
          subPath: content
          readOnly: false

      - name: git-sync-sidecar
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001

        envFrom:
        - secretRef:
            name: git-credentials-repo
        image: ghcr.io/sredevopsdev/git-volumes-synchronizer:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - |
              cd /git/content && git rev-parse --is-inside-work-tree && git status || exit 1
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - |
              cd /git/content && git rev-parse --is-inside-work-tree && git status || exit 1
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /git
          mountPropagation: HostToContainer
          name: mysql-gitsync-vol
          readOnly: false

      dnsPolicy: ClusterFirst

      initContainers:
      - name: git-sync-init
        envFrom:
        - secretRef:
            name: git-credentials-repo
        image: ghcr.io/sredevopsdev/git-volumes-synchronizer:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001

        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi

        volumeMounts:
        - mountPath: /git
          mountPropagation: HostToContainer
          name: mysql-gitsync-vol
          readOnly: false


      nodeSelector:
        kubernetes.io/arch: amd64

      restartPolicy: Always

      volumes:
      - emptyDir:
          sizeLimit: 5Gi
        name: mysql-gitsync-vol

      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001


  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
