apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-gitsync
  namespace: gitsync
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: mysql-gitsync

  serviceName: mysql-gitsync
  template:
    metadata:
      labels:
        app: mysql-gitsync
      namespace: gitsync
    spec:
      securityContext:
        fsGroup: 1001

      initContainers:
      - name: git-sync-init
        envFrom:
        - secretRef:
            name: git-credentials-repo
        image: ghcr.io/sredevopsdev/git-volumes-synchronizer:tests
        # image: bitnami/git:2-debian-11
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          #readOnlyRootFilesystem: true
          #runAsNonRoot: true

        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi

        volumeMounts:
        - mountPath: /git
          mountPropagation: HostToContainer
          name: mysql-gitsync-vol
          readOnly: false


      containers:
      - name: mysql-gitsync
        envFrom:
        - secretRef:
            name: gitsync-mysql-credentials
        image: docker.io/mysql/mysql-server:8.0.32-1.2.11-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          name: mysql-gs
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "0"
            memory: "0"
        securityContext:
          allowPrivilegeEscalation: false
          #readOnlyRootFilesystem: true
          #runAsNonRoot: true

        volumeMounts:
        - mountPath: /var/lib/mysql
          mountPropagation: HostToContainer
          name: mysql-gitsync-vol
          subPath: content
          readOnly: false

      - name: git-sync-sidecar
        securityContext:
          allowPrivilegeEscalation: false
          #readOnlyRootFilesystem: true
          #runAsNonRoot: true

        envFrom:
        - secretRef:
            name: git-credentials-repo
        image: ghcr.io/sredevopsdev/git-volumes-synchronizer:tests
        # image: bitnami/git:2-debian-11
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /git
          mountPropagation: HostToContainer
          name: mysql-gitsync-vol
          readOnly: false


      dnsPolicy: ClusterFirst




      nodeSelector:
        kubernetes.io/arch: amd64

      restartPolicy: Always

      volumes:
      - name: mysql-gitsync-vol
        emptyDir:
          sizeLimit: 5Gi
