apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghostk3s
  namespace: gitsync
spec:
  selector:
    matchLabels:
      app: ghostk3s
  replicas: 1
  template:
    metadata:
      namespace: gitsync
      labels:
        app: ghostk3s
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector:
        kubernetes.io/arch: amd64

      volumes:
      - name: ghost-from-git
        emptyDir:
          sizeLimit: 5Gi


      - name: ghost-config-prod
        secret:
          secretName: ghost-config-prod

      - name: tmp
        emptyDir:
          medium: ""
          sizeLimit: "512Mi"


      initContainers:
      - name: git-sync-init
        image: ghcr.io/sredevopsdev/git-volumes-synchronizer:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: git-sync-ghost # git-credentials-repo is the name of the secret containing the git credentials GITSYNC_PASSWORD and GITSYNC_USERNAME
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: ghost-from-git
          mountPath: /git # this is the path where the git-sync container will store the mysql data
          readOnly: false
          mountPropagation: HostToContainer




      containers:
      - name: ghostk3s
        image: ghcr.io/sredevopsdev/ghost-on-kubernetes:main
        imagePullPolicy: Always
        resources:
          requests:
            memory: 1Gi
            cpu: 1000m
          limits:
            memory: 2Gi
            cpu: 2000m
        securityContext:
          # capabilities:
          #   drop:
          #     - all
          #   add:
          #     - CHOWN
          #     - DAC_OVERRIDE
          #     - SETGID
          #     - SETUID
          #     - SETPCAP
          #     - NET_BIND_SERVICE
          # runAsUser: 10001
          # runAsGroup: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false

        ports:
        - containerPort: 2368
          protocol: TCP
          name: ghostk3s
        env:
        - name: NODE_ENV
          value: production
        volumeMounts:
        - name: ghost-from-git
          mountPath: /var/lib/ghost/content
          subPath: git/content
          readOnly: false
          mountPropagation: HostToContainer

        - name: ghost-config-prod
          mountPath: /var/lib/ghost/config.production.json
          subPath: config.production.json
          readOnly: true

        - name: tmp
          mountPath: /tmp
          readOnly: false
      # sidecarContainers:
      - name: git-sync-sidecar
        image: ghcr.io/sredevopsdev/git-volumes-synchronizer:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: git-sync-ghost # git-credentials-repo is the name of the secret containing the git credentials GITSYNC_PASSWORD and GITSYNC_USERNAME
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: ghost-from-git
          mountPath: /git # this is the path where the git-sync container will store the mysql data
          readOnly: false
          mountPropagation: HostToContainer



