name: Build and push image to DockerHub and GitHub Container Registry

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
      - '.github/workflows/build-custom-image.yaml'

  workflow_dispatch:
    inputs:
      manual-tag:
        description: 'Manual Tag'
        required: true
        default: 'main'
        type: string
    #   ghost_version:
    #     description: 'Ghost version'
    #     required: true
    #     default: '5.54.0'
    #     type: string

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
    
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: |
            linux/amd64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            docker.io/${{ secrets.DOCKER_USER }}/${{ github.event.repository.name }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag
            type=raw,value=${{ github.event.inputs.manual-tag }}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=git-volumes-synchronizer
            org.opencontainers.image.vendor=https://sredevops.org
            org.opencontainers.image.source=https://github.com/sredevopsdev/git-volumes-synchronizer
            org.opencontainers.image.documentation=https://github.com/sredevopsdev/git-volumes-synchronizer/blob/main/README.md
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}          
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}
          cache-to: type=inline
          